### ISSUE TITLE
DENY all traffic from other namespaces

### ISSUE THREAD

**Issue by raniatriki** [ahmetb/kubernetes-network-policy-recipes#11]
Hello,

I am trying to deny traffic from other pods from other namespaces but that doesn't work for me!!

I'm using Weave-Net like Network plugin and i'm following this document: https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/04-deny-traffic-from-other-namespaces.md

Any help!!

Thank you

**Comment by ahmetb** [comment]
@raniatriki as you can imagine, your error report isn't very useful to me. 

Please tell more about:
- what you tried (link to your manifests and policy you deployed) and
- "what" didn't work, what were you expecting, what happened

**Comment by ehernandez-xk** [comment]
Maybe is a good idea to create an issue template for this awesome repo!

**Comment by ahmetb** [comment]
Maybe.

I'm not sure I want this repo to turn into a "network policy support forum". I may therefore actually turn off the issue tracker, and if they think something is broken, they can send a PR.

For now it’s too extreme as I'm not getting too many issues. For the problem above, I'm fairly confident that the policy is correct. So it's either (1) PEBKAC (2) some issue with Weave or its configuration.

**Comment by raniatriki** [comment]
@ahmetb  i'm trying this network policy yaml file : 
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: secondary
  name: web-deny-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
```

Then when I query the web service (that i have created before in a namespace called secondary) , the traffic is not blocked from  another namespace
