### ISSUE TITLE
Wrong DENY external egress traffic NetworkPolicy

### ISSUE THREAD

**Issue by sim500** [ahmetb/kubernetes-network-policy-recipes#111]
I think the NetworkPolicy proposed [here](https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/14-deny-external-egress-traffic.md) is wrong. You have to allow traffic to private IPs if you want to allow inter-pod communication.
So I'd edit the policy in something like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: foo-deny-external-egress
spec:
  podSelector:
    matchLabels:
      app: foo
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    - ipBlock:
        cidr: 10.0.0.0/8
    - ipBlock:
       cidr: 172.16.0.0/12
    - ipBlock:
        cidr: 192.168.0.0/16
```
