### ISSUE TITLE
Will something like this work ? 

### ISSUE THREAD

**Issue by mhobotpplnet** [ahmetb/kubernetes-network-policy-recipes#19]
Am including 
Allow ingress from these namespaces AND these cidrs. or do I need to split that into two yaml? 
Let me know if this is ok to post here or shall I go to k8 community.  
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: my-default-policy
  name: deny-traffic-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - ipBlock:
        cidr: 172.44.0.0/16
    - namespaceSelector:
        matchLabels:
          name: ingress-traffic
    - namespaceSelector:
        matchLabels:
          name: ingress-internet
    - podSelector: {}
```

**Comment by ahmetb** [comment]
Seems ok. Did you watch my talk on the README.md? Note that these ingress rules will be OR’ed and not AND’ed.

**Comment by ahmetb** [comment]
Also you should deploy and test instead of speculating. 😊

**Comment by mhobotpplnet** [comment]
I deployed it :) struggling with for few days now. Testing it like crazy. But still no luck. 

Issue I have is:  As soon as I apply the ingress rule above, all apps within those namespaces can talk to app in `my-default-policy` but anything outside k8 cluster can't - added the cidr from my aws and still no luck, tried checking out the iptables and have not found dropped traffic yet. 
Node that pod is on shows only connections from other nodes. 

Yeah I read your readme - thats why I was bit confused why its not working lol.

**Comment by ahmetb** [comment]
It looks like you’re not declaring any ports. (i assume you omitted them?)

Some network plugins require you to whitelist the containerPort specified on the Service , and some require you to specify the targetPort.

I haven’t tested the “allowing selective traffic from outsite the cluster” aspect well. But if you learn something, I’d be interested.

**Comment by mhobotpplnet** [comment]
That was my next line . 
Adding ports like this , so basically all ports , hope thats right.. -- the network policy on k8 is not much helpful. Calico wants to implement their own network policies ... so am in limbo .. 

```
     - namespaceSelector:
         matchLabels:
           name: ingress-intranet
     - podSelector: {}
    ports:
    - protocol: TCP
      port: {}
```

I'll def share all the findings.
