### ISSUE TITLE
Cannot DENY external egress traffic

### ISSUE THREAD

**Issue by jayhenry** [ahmetb/kubernetes-network-policy-recipes#25]
My k8s cluster is 1.8.5. And I did things following https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/14-deny-external-egress-traffic.md

But when I run a pod as `kubectl run --rm --restart=Never --image=alpine -i -t -l app=foo test -- ash` and run `wget -O- --timeout 1 http://www.bing.com` I can still get the response. It doesn't deny the external egress traffic of this pod. 

Anything is wrong? The k8s version 1.8.5 ?

**Comment by ahmetb** [comment]
Have you installed network plugin to your cluster?

**Comment by jayhenry** [comment]
Yes, I did.  They are running
```
kube-system   calico-node-fmw5z                           2/2       Running   0          1d
kube-system   calico-node-qq577                           2/2       Running   0          1d
kube-system   calico-policy-controller-6c4f86fb54-gz7cp   1/1       Running   0          1d
```
And I can control the egresss traffic among the cluster. For example, apply the following policy
```
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: default
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: ns-calico2
    ports:
    - protocol: UDP
      port: 53
``` 
The pod running in default namespace can ping pods in ns-calico2 namespace, but can't ping pods in ns-calico1 namespaces.
However, it can still ping www.bing.com. I can't controll its external egress traffic.
