### ISSUE TITLE
ALLOW Traffic from DMZ Namespace (nginx ingress controller) to Kubernetes API (IP: 10.233.0.1:443) How?

### ISSUE THREAD

**Issue by de1m** [ahmetb/kubernetes-network-policy-recipes#26]
I've created the default rule to deny all traffic from DMZ Namespace:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-from-dmz
  namespace: dmz
spec:
  podSelector: {}
  policyTypes:
  - Egress
```
But now I need the access to the service "default/kubernetes" this service forward the traffik to node IP:443
```
ceku@ceku1 /a/r/network-policies> kubectl describe svc kubernetes
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                10.233.0.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         192.168.49.201:6443,192.168.49.202:6443,192.168.49.203:6443
Session Affinity:  ClientIP
Events:            <none>
```
How can I allow  the access from "nginx ingress controller" to this api?
My test policy (but not working):
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingresscontroller-dmz-to-pods
  namespace: dmz
spec:
  podSelector:
    matchLabels:
      k8s-app: nginx-ingress-controller-dmz
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: dmz
  - to:
    - ipBlock:
        cidr: 10.233.0.1/32
        cidr: 192.168.49.201/32
        cidr: 192.168.49.202/32
        cidr: 192.168.49.203/32
    ports:
    - protocol: TCP
      port: 443
  ingress:
  - from: []
```

**Comment by de1m** [comment]
I've found the solution. The service (default/kubernetes) redirect my request to the node port, so I need a allow rule to the k8s nodes port 6443
My working policy: 
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingresscontroller-dmz-to-pods
  namespace: dmz
spec:
  podSelector:
    matchLabels:
      k8s-app: nginx-ingress-controller-dmz
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: dmz
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
  - to:
    - ipBlock:
        cidr: 10.233.0.1/32
    ports:
    - protocol: TCP
      port: 443
  - to:
    - ipBlock:
        cidr: 192.168.49.201/32
    ports:
    - protocol: TCP
      port: 6443
  - to:
    - ipBlock:
        cidr: 192.168.49.202/32
    ports:
    - protocol: TCP
      port: 6443
  - to:
    - ipBlock:
        cidr: 192.168.49.203/32
    ports:
    - protocol: TCP
      port: 6443
  - to:
    - namespaceSelector:
        matchLabels:
          name: dmz
    ports:
    - protocol: TCP
      port: 10254
  ingress:
  - from: []
```
