### ISSUE TITLE
Mixing Up NetworkPolicies?

### ISSUE THREAD

**Issue by acinwinstack** [ahmetb/kubernetes-network-policy-recipes#36]
As of `v1.10`, is it possible to set up Network Policy to meet requirements below:

- [ ] Pods within namespace A can communicate with each other
- [ ] Pods can't communicate across namespaces (ie. Pods in namespace B cannot communicate pods in namespace A)
- [ ] Pods can allow ingress from the internet
- [ ] Pods cannot allow egress to k8s nodes

So far, the closest I've got is 
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-a-default-network-policy
  namespace: user-a-ns
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: user-a-ns
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 172.16.35.11/32      # K8s Node IPs
        - 172.16.35.12/32
```

This results namespace isolation and k8s node denials, fulfilling three of the requirements listed:

- [x] Pods within namespace A can communicate with each other
- [x] Pods can't communicate across namespaces (ie. Pods in namespace B cannot communicate pods in namespace A)
- [ ] Pods can allow ingress from the internet
- [x] Pods cannot allow egress to k8s nodes

We did think about adding `spec.ingress.from.ipBlock` as below, but it turns out allowing everything from other namespaces... 

```yaml
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    - namespaceSelector:
        matchLabels:
          name: user-a-ns
```

resulting:

- [x] Pods within namespace A can communicate with each other
- [ ] Pods can't communicate across namespaces (ie. Pods in namespace B cannot communicate pods in namespace A)
- [x] Pods can allow ingress from the internet
- [x] Pods cannot allow egress to k8s nodes

I'm really struggling to get all four of the requirements set up. Any help is appreciated.

**Comment by ahmetb** [comment]
You will have better chance of getting an answer at Kubernetes user forums like discuss.k8s.io or slack.k8s.io. The issue tracker is for bugs about this repo.

**Comment by acinwinstack** [comment]
I'm closing this issue due to it's seemingly in the wrong location, and I've also come up with a solution to my own issue. My NetworkPolicy is set as below if anyone's interested:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-a-default-network-policy
  namespace: user-a-ns
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8              # Service ClusterIPs
          - 172.16.35.x/32      # K8s Node IPs
    - namespaceSelector:
        matchLabels:
          name: user-a-ns
```

If all namespaces have such NetworkPolicy set up, so far it's met my requirements.
