### ISSUE TITLE
example with multiple services on different ports ?

### ISSUE THREAD

**Issue by diepes** [ahmetb/kubernetes-network-policy-recipes#50]
Or is it best practice not to filter on ports ?

e.g.
```
- to: 
  - podSelector:
      matchLabels:
        app: mongodb
  ports:
    - protocol: TCP
      port: 27017 #mongo
  - podSelector: # redis p:6379
        matchLabels:
          app: redis      
  ports:
    - protocol: TCP
      port: 6379 #redis

```

**Comment by namloc2001** [comment]
> 
> 
> Or is it best practice not to filter on ports ?
> 
> e.g.
> 
> ```
> - to: 
>   - podSelector:
>       matchLabels:
>         app: mongodb
>   ports:
>     - protocol: TCP
>       port: 27017 #mongo
>   - podSelector: # redis p:6379
>         matchLabels:
>           app: redis      
>   ports:
>     - protocol: TCP
>       port: 6379 #redis
> ```

Are you looking for something like this? (Note: this has been created as specific to a namespace and then using namespace selectors for egress, however they could be dropped if not required).

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: project-1
  name: project-1.network-policy
spec:
  podSelector:
    matchLabels:
      app: my-app
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          namespace: other-namespace  
      podSelector:
         matchLabels:
           app: Mongo
    ports:
    - protocol: TCP
      port: 27017 
  - to:
    - namespaceSelector:
        matchLabels:
          namespace: other-namespace
      podSelector:
        matchLabels:
          app: Redis    
    ports:
    - protocol: TCP
      port: 6379
  policyTypes:
  - Egress

**Comment by diepes** [comment]
Ok, but if you operating in a single namespace, and add NetworkPolicy.
You should use multiple **- to:** entries, i think i missed that.

My example with additional -to:

```
- to: 
  - podSelector:
      matchLabels:
        app: mongodb
  ports:
    - protocol: TCP
      port: 27017 # mongo

- to:
  - podSelector: # redis p:6379
        matchLabels:
          app: redis      
  ports:
    - protocol: TCP
      port: 6379 #redis

```
