### ISSUE TITLE
Block all port except specified.

### ISSUE THREAD

**Issue by vrathore18** [ahmetb/kubernetes-network-policy-recipes#59]
First of all, I like to thank you for this project. I know this is not a place for support but could you also add another example similar to below.  

Here we blocking all port except 53(TCP and UDP). How to do all allow except 53. I tired action: deny but it's NOT working.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: foo-deny-external-egress
spec:
  podSelector:
    matchLabels:
      app: foo
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
   to:
    - namespaceSelector: {}
```
