### ISSUE TITLE
Document CIDR blocks

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/kubernetes-network-policy-recipes#6]

**Comment by de1m** [comment]
The Network Policy below allow access to all, exept internal networks (192.168.0.0/16 and 172.23.40.0/24)
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-external
  namespace: dmz
spec:
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 192.168.0.0/16
        - 172.23.42.0/24
    - namespaceSelector:
        matchLabels:
          name: dmz
```
