### ISSUE TITLE
2a and 5 seem to be duplicates of each other, but with different explanations -- should they be combined?

### ISSUE THREAD

**Issue by mattfenwick** [ahmetb/kubernetes-network-policy-recipes#60]
Apologies if I'm wrong about this, network policies are hard to grok :) 

As far as I can tell, [example 2a](https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/02a-allow-all-traffic-to-an-application.md):

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-allow-all
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: web
  ingress:
  - {}
```

and [example 5](https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/05-allow-traffic-from-all-namespaces.md):

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: secondary
  name: web-allow-all-namespaces
spec:
  podSelector:
    matchLabels:
      app: web
  ingress:
  - from:
    - namespaceSelector: {}
```

do the same thing as each other.  Maybe their explanations should be merged, and the merged page could include examples of the various ways to specify "all pods and all namespaces" for ingress?  (I think I have 4 already :) )

Happy to pick this up and put together a PR for this -- assuming I've understood both examples correctly!
