### ISSUE TITLE
ALLOW traffic to an application from all namespaces - create deny-all ing policy

### ISSUE THREAD

**Issue by surajssd** [ahmetb/kubernetes-network-policy-recipes#80]
In the case of ["ALLOW traffic to an application from all namespaces"](https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/05-allow-traffic-from-all-namespaces.md) we need to create a deny-all-ingress policy to deny other traffic. Just creating an allow-all-traffic-from-all-ns-to-web is not enough.

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
```
